"""Generate readable event IDs and pair map from the typed stage enum; CPU only."""
from config_io import load_config
import json,re
from pathlib import Path

def generate(source, output):
    output.mkdir(parents=True, exist_ok=True)
    text=re.sub(r'//[^\n]*|/\*.*?\*/','',source.read_text(),flags=re.S)
    body=re.search(r'enum\s+MoeProfileStage\s*:\s*uint32_t\s*\{(.*?)\}',text,re.S)
    if not body:raise ValueError('MoeProfileStage enum not found')
    entries=[];used=set();names=set()
    for item in body[1].split(','):
        if not item.strip():continue
        match=re.fullmatch(r'\s*([A-Z][A-Z0-9_]*)\s*=\s*(0x[0-9a-fA-F]+|[0-9]+)\s*',item)
        if not match:raise ValueError('Use NAME = stable_integer_id for each stage')
        name,value=match.groups();begin=int(value,0);end=0xff if name=='KERNEL' else begin+1
        if name in names or begin in used or end in used or begin==end or not 0<=begin<end<=0xffffffff:
            raise ValueError('Duplicate/overlapping/out-of-range stage IDs: '+name)
        names.add(name);used.update((begin,end));entries.append((name,begin,end))
    if not entries:raise ValueError('Empty stage enum')
    header='// Generated by scripts/generate_profile_events.py. Edit profile_stages.h.\n#pragma once\n#include "profile_stages.h"\n'
    header+='enum ProfEventId : uint32_t {\n'
    header+=''.join(f'    {n}_BEGIN = 0x{b:04x}, {n}_END = 0x{e:04x},\n' for n,b,e in entries)+'};\n'
    header+='''namespace MoeProfile {
__aicore__ inline constexpr uint32_t BeginId(MoeProfileStage stage) {
    return static_cast<uint32_t>(stage);
}
__aicore__ inline constexpr uint32_t EndId(MoeProfileStage stage) {
    return stage == KERNEL ? 0x00ff : static_cast<uint32_t>(stage) + 1;
}
}
'''
    outputs={output/'profile_events_generated.h':header,
             output/'pair_map.json':json.dumps({f'0x{b:04x}':f'0x{e:04x}' for _,b,e in entries},indent=2)+'\n'}
    for path,data in outputs.items():
        if not path.exists() or path.read_text()!=data:path.write_text(data)
    return len(entries)

if __name__=='__main__':
    import argparse
    p=argparse.ArgumentParser()
    p.add_argument('--stages',type=Path,required=True)
    p.add_argument('--output',type=Path,required=True)
    p.add_argument('--config',type=Path,required=True)
    a=p.parse_args()
    generate(a.stages,a.output)
    c=load_config(a.config);case=c['case'];device=c['device']
    case.setdefault('shared_experts', 0)
    defs={**{k.upper():v for k,v in case.items() if isinstance(v,int)},'AIC':device['aic_cores'],'AIV':device['aiv_cores']}
    text='#pragma once\n'+''.join(f'#define PROFILE_{k} {v}\n' for k,v in defs.items())
    weight,quant={'fp8_e5m2':('fp8_e5m2_t','E5M2_QUANT'),'fp8_e4m3fn':('fp8_e4m3fn_t','E4M3_QUANT')}[case['dtype']]
    text+=f'#define PROFILE_WEIGHT_TYPE {weight}\n#define PROFILE_QUANT {quant}\n'
    text+=f'#define PROFILE_PLATFORM "{c["build"]["platform"]}"\n'
    a.output.joinpath('case_config.h').write_text(text)
    a.output.joinpath('profiler_config.h').write_text('#pragma once\n'+f'#define PROF_N_CORES {device["aic_cores"]+device["aiv_cores"]}\n#define PROF_AIV_CORES {device["aiv_cores"]}\n#define PROF_SLOTS_PER_CORE {device["slots_per_core"]}\n#define PROF_RECORD_BYTES 16\n#define PROF_RINGIDX_ALIGN 64\n')
